# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9410e67126cfecb4e0a10c39a673825bd921572b89ba23108d8560d15f38972ac25637293f4823cb6884d4c045bc42d5516ff1aa1e1462c8ec77bbe4a4b70b46

test:
  secret_key_base: 8edcec85a2d943bdbd7e29e0238fbf569d8ed6c2ec78aaaff63e8f1fbf0c19cd8b410545d3ccef323e7bbac2664ac231d115e7f7466a4640d417fe2ff606c99e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
